(function(){
 'use strict';
 const data=window.WallfidLanguages,records=new WeakMap(),attributeRecords=new WeakMap();
 const source=data.translations.en,entries=Object.keys(source),exact=new Set(entries);
 let locale='en';try{const saved=localStorage.getItem('wallfid.language');if(data.translations[saved])locale=saved;}catch{}
 const escape=s=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
 function compile(text){const names=[];let at=0,pattern='';for(const m of text.matchAll(/\{(\w+)\}/g)){pattern+=escape(text.slice(at,m.index));names.push(m[1]);pattern+=['name','letter'].includes(m[1])?'(.+?)':'([\\d.,]+)';at=m.index+m[0].length;}return {regex:new RegExp('^'+pattern+escape(text.slice(at))+'$'),names};}
 const templates=entries.filter(k=>k.includes('{')).sort((a,b)=>b.length-a.length).map(key=>({key,...compile(key)}));
 function interpolate(text,params){return text.replace(/\{(\w+)\}/g,(_,name)=>params[name]??'{'+name+'}');}
 function identify(text){if(exact.has(text))return {key:text,params:{}};for(const item of templates){const m=text.match(item.regex);if(m)return {key:item.key,params:Object.fromEntries(item.names.map((n,i)=>[n,m[i+1]]))};}return null;}
 function translate(text){const hit=identify(text);if(!hit)return text;const params={...hit.params};if(params.name)params.name=translate(params.name);return interpolate(data.translations[locale][hit.key]||hit.key,params);}
 function canonical(text){if(identify(text))return text;const table=data.translations[locale];for(const key of entries){const value=table[key];if(!value)continue;if(!key.includes('{')){if(value===text)return key;}else{const rule=compile(value),m=text.match(rule.regex);if(m){const params=Object.fromEntries(rule.names.map((n,i)=>[n,m[i+1]]));if(key==='Image: {name}')params.name=canonical(params.name);return interpolate(key,params);}}}return text;}
 function processText(node){const raw=node.nodeValue,trimmed=raw.trim();if(!trimmed)return;const prior=records.get(node);const original=prior&&raw===prior.value?prior.original:canonical(trimmed);const value=raw.slice(0,raw.indexOf(trimmed))+translate(original)+raw.slice(raw.indexOf(trimmed)+trimmed.length);records.set(node,{original,value});if(raw!==value)node.nodeValue=value;}
 function processAttributes(el){const stored=attributeRecords.get(el)||{};for(const attr of ['aria-label','title','alt']){if(!el.hasAttribute(attr))continue;const raw=el.getAttribute(attr),prior=stored[attr],original=prior&&raw===prior.value?prior.original:canonical(raw);const value=translate(original);stored[attr]={original,value};if(raw!==value)el.setAttribute(attr,value);}attributeRecords.set(el,stored);}
 function apply(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,{acceptNode(node){const el=node.nodeType===1?node:node.parentElement;if(!el||el.closest('script,style,[data-no-i18n]'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT;}});if(root.nodeType===1)processAttributes(root);let node;while((node=walker.nextNode())){if(node.nodeType===3)processText(node);else processAttributes(node);}}
 function originalText(el){return Array.from(el.childNodes).map(n=>n.nodeType===3?(records.get(n)?.original||canonical(n.nodeValue.trim())):originalText(n)).join('');}
 const observer=new MutationObserver(()=>{observer.disconnect();apply();observe();});
 function observe(){observer.observe(document.body,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','alt']});}
 function update(){observer.disconnect();apply();document.documentElement.lang=locale==='en'?'en-GB':locale;document.title=translate('WALLFID Rhinestone Studio — Your picture. Your sparkle.');document.querySelector('meta[name="description"]').content=translate('Turn your picture into a numbered rhinestone pattern. Choose your acrylic board, use your 40-colour kit, and make it at your own pace.');const chosen=data.languages.find(l=>l.code===locale);document.getElementById('languageCode').textContent=chosen.short;document.getElementById('languageButton').setAttribute('aria-label',translate('Choose your language')+' · '+chosen.name);document.querySelectorAll('[data-language]').forEach(b=>{const active=b.dataset.language===locale;b.setAttribute('aria-pressed',String(active));b.querySelector('span').textContent=active?'✓':'';});observe();}
 function choose(code){if(!data.translations[code])return;locale=code;try{localStorage.setItem('wallfid.language',code);}catch{}update();document.getElementById('languageDialog').close();document.getElementById('languageButton').focus({preventScroll:true});}
 // Canvas exports translate synchronously; shrink long labels to their allocated width.
 function drawText(g,text,x,y){let value=translate(String(text)),max=x>70?285:1260;const font=g.font,size=Number(font.match(/([\d.]+)px/)?.[1]||18),width=g.measureText(value).width;if(width>max)g.font=font.replace(/([\d.]+)px/,(Math.max(11,size*max/width))+'px');g.fillText(value,x,y,max);g.font=font;}
 window.WallfidI18n={translate,apply,originalText,drawText};
 const list=document.getElementById('languageList');data.languages.forEach(language=>{const b=document.createElement('button');b.type='button';b.dataset.language=language.code;b.lang=language.code;b.append(document.createTextNode(language.name),document.createElement('span'));b.addEventListener('click',()=>choose(language.code));list.append(b);});
 document.getElementById('languageButton').addEventListener('click',()=>document.getElementById('languageDialog').showModal());document.getElementById('closeLanguage').addEventListener('click',()=>document.getElementById('languageDialog').close());
 update();
})();
